SecondAmendment.AddSound("UZI", "Fire", "weapons/cmb/uzi/fire.wav")
SecondAmendment.AddSound("UZI", "ClipOut", "weapons/cmb/uzi/clipout.wav")
SecondAmendment.AddSound("UZI", "ClipIn", "weapons/cmb/uzi/clipin.wav")
SecondAmendment.AddSound("UZI", "BoltBack", "weapons/cmb/uzi/boltback.wav")
SecondAmendment.AddSound("UZI", "BoltForward", "weapons/cmb/uzi/boltforward.wav")
SecondAmendment.AddSound("UZI", "Tap", "weapons/cmb/uzi/tap.wav")

SecondAmendment.AddSound("Xbow", "Fire", "weapons/viper/xbow/fire.wav")
SecondAmendment.AddSound("Xbow", "String", "weapons/viper/xbow/stringdrawback.wav")
SecondAmendment.AddSound("Xbow", "Load", "weapons/viper/xbow/load.wav")
SecondAmendment.AddSound("Xbow", "Draw", "weapons/viper/xbow/draw.wav")

SecondAmendment.AddSound("M4", "Fire", "weapons/cmb/m4/fire1.wav", "weapons/cmb/m4/fire2.wav", "weapons/cmb/m4/fire3.wav" )
SecondAmendment.AddSound("M4", "ClipOut", "weapons/cmb/m4/magout.wav")
SecondAmendment.AddSound("M4", "ClipIn", "weapons/cmb/m4/magin.wav")
SecondAmendment.AddSound("M4", "BoltBack", "weapons/cmb/m4/boltback.wav")
SecondAmendment.AddSound("M4", "BoltForward", "weapons/cmb/m4/boltrelease.wav")

SecondAmendment.AddSound("M16A4", "Fire", "weapons/viper/m16a4/fire1.wav", "weapons/cmb/m4/fire2.wav", "weapons/cmb/m4/fire3.wav" )
SecondAmendment.AddSound("M16A4", "ClipOut", "weapons/viper/m16a4/magout.wav")
SecondAmendment.AddSound("M16A4", "ClipIn", "weapons/viper/m16a4/magin.wav")
SecondAmendment.AddSound("M16A4", "BoltBack", "weapons/viper/m16a4/boltback.wav")
SecondAmendment.AddSound("M16A4", "BoltForward", "weapons/viper/m16a4/boltrelease.wav")

SecondAmendment.AddSound("AKM", "Fire", "weapons/cmb/akm/fire.wav")
SecondAmendment.AddSound("AKM", "ClipOut", "weapons/cmb/akm/magout.wav")
SecondAmendment.AddSound("AKM", "ClipRelease", "weapons/cmb/akm/magrelease.wav")
SecondAmendment.AddSound("AKM", "ClipOutRattle", "weapons/cmb/akm/magoutrattle.wav")
SecondAmendment.AddSound("AKM", "ClipIn", "weapons/cmb/akm/magin.wav")
SecondAmendment.AddSound("AKM", "BoltBack", "weapons/cmb/akm/boltback.wav")
SecondAmendment.AddSound("AKM", "BoltForward", "weapons/cmb/akm/boltrelease.wav")
SecondAmendment.AddSound("AKM", "Rattle", "weapons/cmb/akm/rattle.wav")

SecondAmendment.AddSound("STG", "Fire", "weapons/cmb/stg/fire.wav")
SecondAmendment.AddSound("STG", "ClipOut", "weapons/cmb/stg/magout.wav")
SecondAmendment.AddSound("STG", "ClipIn", "weapons/cmb/stg/magin.wav")
SecondAmendment.AddSound("STG", "BoltBack", "weapons/cmb/stg/boltback.wav")
SecondAmendment.AddSound("STG", "BoltForward", "weapons/cmb/stg/boltrelease.wav")

SecondAmendment.AddSound("SMG1", "Fire", "weapons/viper/smg1/fire.wav")
SecondAmendment.AddSound("SMG1", "ClipOut", "weapons/viper/smg1/magout.wav")
SecondAmendment.AddSound("SMG1", "ClipIn", "weapons/viper/smg1/magin.wav")
SecondAmendment.AddSound("SMG1", "Draw", "weapons/viper/smg1/draw.wav")

SecondAmendment.AddSound("MP5SD", "Fire", "weapons/cmb/mp5sd/fire.wav")
SecondAmendment.AddSound("MP5SD", "ClipOut", "weapons/cmb/mp5sd/magout.wav")
SecondAmendment.AddSound("MP5SD", "ClipIn", "weapons/cmb/mp5sd/magin.wav")

SecondAmendment.AddSound("Browning", "Fire", "weapons/cmb/browning/browning_fp.wav")
SecondAmendment.AddSound("Browning", "MagOut", "weapons/cmb/browning/browning_magout.wav")
SecondAmendment.AddSound("Browning", "MagIn", "weapons/cmb/browning/browning_maghit.wav")
SecondAmendment.AddSound("Browning", "SlideRelease", "weapons/cmb/browning/browning_boltrelease.wav")
SecondAmendment.AddSound("Browning", "SlideBack", "weapons/cmb/browning/browning_boltback.wav")

SecondAmendment.AddSound("9MM", "Fire", "weapons/viper/pistol/fire.wav")
SecondAmendment.AddSound("9MM", "MagOut", "weapons/viper/pistol/magout.wav")
SecondAmendment.AddSound("9MM", "MagIn", "weapons/viper/pistol/magin.wav")
SecondAmendment.AddSound("9MM", "SlideRelease", "weapons/viper/pistol/sliderelease.wav")
SecondAmendment.AddSound("9MM", "Draw", "weapons/viper/pistol/draw.wav")

SecondAmendment.AddSound("Mossberg", "Fire", "weapons/cmb/mossberg/fire.wav")
SecondAmendment.AddSound("Mossberg", "PumpBack", "weapons/cmb/mossberg/pumpback.wav")
SecondAmendment.AddSound("Mossberg", "PumpForward", "weapons/cmb/mossberg/pumpforward.wav")
SecondAmendment.AddSound("Mossberg", "ShellInsert", "weapons/cmb/mossberg/shell.wav")

SecondAmendment.AddSound("Shotgun", "Fire", "weapons/viper/shotgun/fire.wav")
SecondAmendment.AddSound("Shotgun", "PumpBack", "weapons/viper/shotgun/pumpback.wav")
SecondAmendment.AddSound("Shotgun", "PumpForward", "weapons/viper/shotgun/pumpforward.wav")
SecondAmendment.AddSound("Shotgun", "ShellInsert", "weapons/viper/shotgun/shell.wav")
SecondAmendment.AddSound("Shotgun", "Draw", "weapons/viper/shotgun/draw.wav")

SecondAmendment.AddSound("357", "Fire", "weapons/viper/357/fire.wav")
SecondAmendment.AddSound("357", "Reload1", "weapons/viper/357/reload1.wav")
SecondAmendment.AddSound("357", "Reload2", "weapons/viper/357/reload2.wav")
SecondAmendment.AddSound("357", "Reload3", "weapons/viper/357/reload3.wav")
SecondAmendment.AddSound("357", "Reload4", "weapons/viper/357/reload4.wav")
SecondAmendment.AddSound("357", "Draw", "weapons/viper/357/draw.wav")
SecondAmendment.AddSound("357", "Spin", "weapons/viper/357/spin1.wav")

SecondAmendment.AddSound("Remington", "Fire", "weapons/cmb/remington/fire.wav")
SecondAmendment.AddSound("Remington", "BoltBack", "weapons/cmb/remington/boltback.wav")
SecondAmendment.AddSound("Remington", "BoltForward", "weapons/cmb/remington/boltforward.wav")
SecondAmendment.AddSound("Remington", "BoltLatch", "weapons/cmb/remington/boltlatch.wav")
SecondAmendment.AddSound("Remington", "BoltRelease", "weapons/cmb/remington/boltrelease.wav")
SecondAmendment.AddSound("Remington", "MagIn", "weapons/cmb/remington/magin.wav")
SecondAmendment.AddSound("Remington", "MagOut", "weapons/cmb/remington/magout.wav")
SecondAmendment.AddSound("Remington", "MagRelease", "weapons/cmb/remington/magrelease.wav")

SecondAmendment.AddSound("L96", "Fire", "weapons/viper/l96/fire.wav")
SecondAmendment.AddSound("L96", "BoltBack", "weapons/viper/l96/boltback.wav")
SecondAmendment.AddSound("L96", "BoltForward", "weapons/viper/l96/boltforward.wav")
SecondAmendment.AddSound("L96", "BoltLatch", "weapons/viper/l96/boltup.wav")
SecondAmendment.AddSound("L96", "BoltRelease", "weapons/viper/l96/boltdown.wav")
SecondAmendment.AddSound("L96", "MagIn", "weapons/viper/l96/magin.wav")
SecondAmendment.AddSound("L96", "MagOut", "weapons/viper/l96/magout.wav")
SecondAmendment.AddSound("L96", "MagRelease", "weapons/viper/remington/magrelease.wav")

SecondAmendment.AddSound("AR2", "Fire", "weapons/viper/ar2/fire.wav")
SecondAmendment.AddSound("AR2", "Reload_Rotate", "weapons/viper/ar2/reload_rotate.wav")
SecondAmendment.AddSound("AR2", "Rotate", "weapons/viper/ar2/rotate.wav")
SecondAmendment.AddSound("AR2", "Push", "weapons/viper/ar2/push.wav")
SecondAmendment.AddSound("AR2", "Draw", "weapons/viper/ar2/draw.wav")
SecondAmendment.AddSound("AR2", "MagIn", "weapons/viper/ar2/magin.wav")
SecondAmendment.AddSound("AR2", "MagOut", "weapons/viper/ar2/magout.wav")

SecondAmendment.AddSound("Taurus", "Fire", "weapons/cmb/taurus/fire.wav")
SecondAmendment.AddSound("Taurus", "Open", "weapons/cmb/taurus/open.wav")
SecondAmendment.AddSound("Taurus", "Out", "weapons/cmb/taurus/out.wav")
SecondAmendment.AddSound("Taurus", "In", "weapons/cmb/taurus/in.wav")
SecondAmendment.AddSound("Taurus", "Close", "weapons/cmb/taurus/close.wav")

SecondAmendment.AddSound("M67", "Throw", "weapons/cmb/m67/m67_throw.wav")
SecondAmendment.AddSound("M67", "PullPin", "weapons/cmb/m67/m67_pullpin.wav")

SecondAmendment.AddSound("Grenade", "Throw", "weapons/viper/grenade/throw.wav")
SecondAmendment.AddSound("Grenade", "Draw", "weapons/viper/grenade/grenade_draw.wav")
SecondAmendment.AddSound("Grenade", "PullPin", "weapons/viper/grenade/pull.wav")

SecondAmendment.AddSound("Uni", "Foley1", "weapons/cmb/uni/foley1.wav", 0.5)
SecondAmendment.AddSound("Uni", "Foley2", "weapons/cmb/uni/foley2.wav", 0.5)
SecondAmendment.AddSound("Uni", "Foley3", "weapons/cmb/uni/foley3.wav", 0.5)
SecondAmendment.AddSound("Uni", "Foley4", "weapons/cmb/uni/foley4.wav", 0.5)
SecondAmendment.AddSound("Uni", "Foley5", "weapons/cmb/uni/foley6.wav", 0.5)
SecondAmendment.AddSound("Uni", "Foley6", "weapons/cmb/uni/foley6.wav", 0.5)
SecondAmendment.AddSound("Uni", "Foley7", "weapons/cmb/uni/foley7.wav", 0.5)
SecondAmendment.AddSound("Uni", "Tap", "weapons/cmb/uni/tap.wav")
SecondAmendment.AddSound("Uni", "Deploy1", "weapons/cmb/uni/deploy1.wav")
SecondAmendment.AddSound("Uni", "Deploy2", "weapons/cmb/uni/deploy2.wav")
SecondAmendment.AddSound("Uni", "Deploy3", "weapons/cmb/uni/deploy3.wav")

SecondAmendment.AddSound("HL2", "Sprint", "weapons/viper/movement/startsprint.wav")
SecondAmendment.AddSound("HL2", "Foley1", "weapons/viper/movement/weapon_movement1.wav")
SecondAmendment.AddSound("HL2", "Foley2", "weapons/viper/movement/weapon_movement2.wav")
SecondAmendment.AddSound("HL2", "Foley3", "weapons/viper/movement/weapon_movement3.wav")
SecondAmendment.AddSound("HL2", "Foley4", "weapons/viper/movement/weapon_movement4.wav")
SecondAmendment.AddSound("HL2", "Foley5", "weapons/viper/movement/weapon_movement5.wav")
SecondAmendment.AddSound("HL2", "Foley6", "weapons/viper/movement/weapon_movement6.wav")
