SecondAmendment.AddSound("UZI", "Fire", "weapons/cmb/uzi/fire.wav")
SecondAmendment.AddSound("UZI", "ClipOut", "weapons/cmb/uzi/clipout.wav")
SecondAmendment.AddSound("UZI", "ClipIn", "weapons/cmb/uzi/clipin.wav")
SecondAmendment.AddSound("UZI", "BoltBack", "weapons/cmb/uzi/boltback.wav")
SecondAmendment.AddSound("UZI", "BoltForward", "weapons/cmb/uzi/boltforward.wav")
SecondAmendment.AddSound("UZI", "Tap", "weapons/cmb/uzi/tap.wav")

SecondAmendment.AddSound("M4", "Fire", "weapons/cmb/m4/fire1.wav", "weapons/cmb/m4/fire2.wav", "weapons/cmb/m4/fire3.wav" )
SecondAmendment.AddSound("M4", "ClipOut", "weapons/cmb/m4/magout.wav")
SecondAmendment.AddSound("M4", "ClipIn", "weapons/cmb/m4/magin.wav")
SecondAmendment.AddSound("M4", "BoltBack", "weapons/cmb/m4/boltback.wav")
SecondAmendment.AddSound("M4", "BoltForward", "weapons/cmb/m4/boltrelease.wav")

SecondAmendment.AddSound("AKM", "Fire", "weapons/cmb/akm/fire.wav")
SecondAmendment.AddSound("AKM", "ClipOut", "weapons/cmb/akm/magout.wav")
SecondAmendment.AddSound("AKM", "ClipRelease", "weapons/cmb/akm/magrelease.wav")
SecondAmendment.AddSound("AKM", "ClipOutRattle", "weapons/cmb/akm/magoutrattle.wav")
SecondAmendment.AddSound("AKM", "ClipIn", "weapons/cmb/akm/magin.wav")
SecondAmendment.AddSound("AKM", "BoltBack", "weapons/cmb/akm/boltback.wav")
SecondAmendment.AddSound("AKM", "BoltForward", "weapons/cmb/akm/boltrelease.wav")
SecondAmendment.AddSound("AKM", "Rattle", "weapons/cmb/akm/rattle.wav")

SecondAmendment.AddSound("Browning", "Fire", "weapons/cmb/browning/m1911_fp.wav")
SecondAmendment.AddSound("Browning", "MagOut", "weapons/cmb/browning/m1911_magout.wav")
SecondAmendment.AddSound("Browning", "MagIn", "weapons/cmb/browning/m1911_maghit.wav")
SecondAmendment.AddSound("Browning", "SlideRelease", "weapons/cmb/browning/m1911_boltrelease.wav")

SecondAmendment.AddSound("Mossberg", "Fire", "weapons/cmb/mossberg/fire.wav")
SecondAmendment.AddSound("Mossberg", "PumpBack", "weapons/cmb/mossberg/pumpback.wav")
SecondAmendment.AddSound("Mossberg", "PumpForward", "weapons/cmb/mossberg/pumpforward.wav")
SecondAmendment.AddSound("Mossberg", "ShellInsert", "weapons/cmb/mossberg/shell.wav")

SecondAmendment.AddSound("Remington", "Fire", "weapons/cmb/remington/fire.wav")
SecondAmendment.AddSound("Remington", "BoltBack", "weapons/cmb/remington/boltback.wav")
SecondAmendment.AddSound("Remington", "BoltForward", "weapons/cmb/remington/boltforward.wav")
SecondAmendment.AddSound("Remington", "BoltLatch", "weapons/cmb/remington/boltlatch.wav")
SecondAmendment.AddSound("Remington", "BoltRelease", "weapons/cmb/remington/boltrelease.wav")
SecondAmendment.AddSound("Remington", "MagIn", "weapons/cmb/remington/magin.wav")
SecondAmendment.AddSound("Remington", "MagOut", "weapons/cmb/remington/magout.wav")
SecondAmendment.AddSound("Remington", "MagRelease", "weapons/cmb/remington/magrelease.wav")

SecondAmendment.AddSound("Taurus", "Fire", "weapons/cmb/taurus/fire.wav")
SecondAmendment.AddSound("Taurus", "Open", "weapons/cmb/taurus/open.wav")
SecondAmendment.AddSound("Taurus", "Out", "weapons/cmb/taurus/out.wav")
SecondAmendment.AddSound("Taurus", "In", "weapons/cmb/taurus/in.wav")
SecondAmendment.AddSound("Taurus", "Close", "weapons/cmb/taurus/close.wav")

SecondAmendment.AddSound("M67", "Throw", "weapons/cmb/m67/m67_throw.wav")
SecondAmendment.AddSound("M67", "PullPin", "weapons/cmb/m67/m67_pullpin.wav")

SecondAmendment.AddSound("Uni", "Foley1", "weapons/cmb/uni/foley1.wav", 0.5)
SecondAmendment.AddSound("Uni", "Foley2", "weapons/cmb/uni/foley2.wav", 0.5)
SecondAmendment.AddSound("Uni", "Foley3", "weapons/cmb/uni/foley3.wav", 0.5)
SecondAmendment.AddSound("Uni", "Foley4", "weapons/cmb/uni/foley4.wav", 0.5)
SecondAmendment.AddSound("Uni", "Foley5", "weapons/cmb/uni/foley6.wav", 0.5)
SecondAmendment.AddSound("Uni", "Foley6", "weapons/cmb/uni/foley6.wav", 0.5)
SecondAmendment.AddSound("Uni", "Foley7", "weapons/cmb/uni/foley7.wav", 0.5)
SecondAmendment.AddSound("Uni", "Tap", "weapons/cmb/uni/tap.wav")
SecondAmendment.AddSound("Uni", "Deploy1", "weapons/cmb/uni/deploy1.wav")
SecondAmendment.AddSound("Uni", "Deploy2", "weapons/cmb/uni/deploy2.wav")
SecondAmendment.AddSound("Uni", "Deploy3", "weapons/cmb/uni/deploy3.wav")